// UI
export const SET_SYS_MENU_EXPAND = 'SET_SYS_MENU_EXPAND';
export const SET_NAV_MENU_EXPAND = 'SET_NAV_MENU_EXPAND';
export const SYS_MENU_ITEM_CLICKED = 'SYS_MENU_ITEM_CLICKED';
export const SET_LOGIN_DIALOG_VISIBILITY = 'SET_LOGIN_DIALOG_VISIBILITY';
export const SET_EXPORT_DIALOG_VISIBILITY = 'SET_EXPORT_DIALOG_VISIBILITY';
export const SET_ADD_REMOVE_STATION_DIALOG_VISIBILITY = 'SET_ADD_REMOVE_STATION_DIALOG_VISIBILITY';
export const SET_ADD_REMOVE_QUESTION_DIALOG_VISIBILITY = 'SET_ADD_REMOVE_QUESTION_DIALOG_VISIBILITY';
export const SET_SETTINGS_DIALOG_VISIBILITY = 'SET_SETTINGS_DIALOG_VISIBILITY';
export const SET_ABOUT_DIALOG_VISIBILITY = 'SET_ABOUT_DIALOG_VISIBILITY';
export const SET_SWITCH_USER_DIALOG_VISIBILITY = 'SET_SWITCH_USER_DIALOG_VISIBILITY';
export const SET_APP_BAR_TEXT = 'SET_APP_BAR_TEXT';
export const SHOW_NAVIGATION_TABS = 'SHOW_NAVIGATION_TABS';
export const HIDE_NAVIGATION_TABS = 'HIDE_NAVIGATION_TABS';
export const SHOW_PANELS = 'SHOW_PANELS';
export const HIDE_PANELS = 'HIDE_PANELS';
export const SHOW_QUESTIONS = 'SHOW_QUESTIONS';
export const HIDE_QUESTIONS = 'HIDE_QUESTIONS';


// SedFF
export const SET_CURRENT_USERNAME = 'SET_CURRENT_USERNAME';
export const SET_CURRENT_SAMPLING_EVENT = 'SET_CURRENT_SAMPLING_EVENT';
export const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
export const USER_DATA_LOAD_COMPLETE = 'USER_DATA_LOAD_COMPLETE';
export const SAMPLING_EVENTS_REQUEST = 'SAMPLING_EVENTS_REQUEST';
export const SAMPLING_EVENTS_LOAD_COMPLETE = 'SAMPLING_EVENTS_LOAD_COMPLETE';
export const SAMPLING_EVENT_REQUEST = 'SAMPLING_EVENT_REQUEST';
export const SAMPLING_EVENT_LOAD_COMPLETE = 'SAMPLING_EVENT_LOAD_COMPLETE';
export const RUN_ALL_SAMPLE_EVENT_QUESTION_ACTIONS = 'RUN_ALL_SAMPLE_EVENT_QUESTION_ACTIONS';

// DB
export const SYNC_ALL_TO_DB = 'SYNC_ALL_TO_DB';

// Users
export const SET_OUTLINE_QUESTIONS = 'SET_OUTLINE_QUESTIONS';
export const SET_BACKUP_INTERVAL = 'SET_BACKUP_INTERVAL';
export const SET_SEDLOGIN_USERNAME = 'SET_SEDLOGIN_USERNAME';
export const SET_USER_DATA = 'SET_USER_DATA';
export const MAKE_NEW_USER = 'MAKE_NEW_USER';

// SamplingEvents
export const CREATE_NEW_SAMPLING_EVENT = 'CREATE_NEW_SAMPLING_EVENT';
export const SE_QUESTION_VALUE_CHANGE = 'SE_QUESTION_VALUE_CHANGE';
export const SE_QUESTION_VALUE_DELETE = 'SE_QUESTION_VALUE_DELETE';

// LinkTables
export const REGISTER_EVENT_WITH_USERNAME = 'REGISTER_EVENT_WITH_USERNAME';
export const REMOVE_STATION_FROM_USERNAME = 'REMOVE_STATION_FROM_USERNAME';
export const REGISTER_STATION_WITH_USERNAME = 'REGISTER_STATION_WITH_USERNAME';

// Stations
export const SET_STATION_VALUES = 'SET_STATION_VALUES';

// Questions
export const RESET_QUESTIONS_DATA_TO_DEFAULT = 'RESET_QUESTIONS_DATA_TO_DEFAULT';
export const ADD_QUESTION_TO_USER = 'ADD_QUESTION_TO_USER';
export const ADD_QUESTION_TO_QUESTIONS_DATA = 'ADD_QUESTION_TO_QUESTIONS_DATA';
export const ADD_QUESTION_TO_EVENT = 'ADD_QUESTION_TO_EVENT';
export const ADD_QUESTION_TO_STATION = 'ADD_QUESTION_TO_STATION';
export const DELETE_QUESTION_FROM_USER = 'DELETE_QUESTION_FROM_USER';
export const DELETE_QUESTION_FROM_EVENT = 'DELETE_QUESTION_FROM_EVENT';
export const DELETE_QUESTION_FROM_STATION = 'DELETE_QUESTION_FROM_STATION';





