// UI
export const SET_SYS_MENU_EXPAND = 'SET_SYS_MENU_EXPAND';
export const SET_NAV_MENU_EXPAND = 'SET_NAV_MENU_EXPAND';
export const SYS_MENU_ITEM_CLICKED = 'SYS_MENU_ITEM_CLICKED';
export const SET_LOGIN_DIALOG_VISIBILITY = 'SET_LOGIN_DIALOG_VISIBILITY';
export const SET_EXPORT_DIALOG_VISIBILITY = 'SET_EXPORT_DIALOG_VISIBILITY';
export const SET_ADD_REMOVE_STATION_DIALOG_VISIBILITY = 'SET_ADD_REMOVE_STATION_DIALOG_VISIBILITY';
export const SET_ADD_REMOVE_QUESTION_DIALOG_VISIBILITY = 'SET_ADD_REMOVE_QUESTION_DIALOG_VISIBILITY';
export const SET_SETTINGS_DIALOG_VISIBILITY = 'SET_SETTINGS_DIALOG_VISIBILITY';
export const SET_ABOUT_DIALOG_VISIBILITY = 'SET_ABOUT_DIALOG_VISIBILITY';
export const SET_SWITCH_USER_DIALOG_VISIBILITY = 'SET_SWITCH_USER_DIALOG_VISIBILITY';

// SedFF
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// DB
export const SYNC_ALL_TO_DB = 'SYNC_ALL_TO_DB';