// UI
export const SET_SYS_MENU_EXPAND = 'SET_SYS_MENU_EXPAND';
export const SET_NAV_MENU_EXPAND = 'SET_NAV_MENU_EXPAND';
export const SYS_MENU_ITEM_CLICKED = 'SYS_MENU_ITEM_CLICKED';
export const SET_LOGIN_DIALOG_VISIBILITY = 'SET_LOGIN_DIALOG_VISIBILITY';

// User
export const SET_CURRENT_USER = 'SET_CURRENT_USER';